// Post
export const GET_LIST_POST = 'GET_LIST_POST';
export const GET_LIST_POST_SUCCESS = 'GET_LIST_POST_SUCCESS';
export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
// Category
export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const GET_LIST_CATEGORY_SUCCESS = 'GET_LIST_CATEGORY_SUCCESS';
// Tag
export const GET_LIST_POST_TAG = 'GET_LIST_POST_TAG';
export const GET_LIST_POST_TAG_SUCCESS = 'GET_LIST_POST_TAG_SUCCESS';
export const CREATE_POST_TAG = 'CREATE_POST_TAG';
export const CREATE_POST_TAG_SUCCESS = 'CREATE_POST_TAG_SUCCESS';
export const UPDATE_POST_TAG = 'UPDATE_POST_TAG';
export const UPDATE_POST_TAG_SUCCESS = 'UPDATE_POST_TAG_SUCCESS';
export const POST_FAILED = 'POST_FAILED';
