// Hotel
export const GET_ALL_HOTEL = 'GET_ALL_HOTEL';
export const GET_ALL_HOTEL_SUCCESS = 'GET_ALL_HOTEL_SUCCESS';
// Type
export const GET_ALL_TYPE = 'GET_ALL_TYPE';
export const GET_ALL_TYPE_SUCCESS = 'GET_ALL_TYPE_SUCCESS';
// Attribute
export const GET_ATTRIBUTE_HOTEL = 'GET_ATTRIBUTE_HOTEL';
export const GET_ATTRIBUTE_HOTEL_SUCCESS = 'GET_ATTRIBUTE_HOTEL_SUCCESS';
export const HOTEL_ERROR = 'HOTEL_ERROR';
