// Hotel
export const GET_ALL_HOTEL = 'GET_ALL_HOTEL';
export const GET_ALL_HOTEL_SUCCESS = 'GET_ALL_HOTEL_SUCCESS';
export const CREATE_HOTEL = 'CREATE_HOTEL';
export const CREATE_HOTEL_SUCCESS = 'CREATE_HOTEL_SUCCESS';
export const UPDATE_HOTEL = 'UPDATE_HOTEL';
export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS';
export const GET_HOTEL = 'GET_HOTEL';
export const GET_HOTEL_SUCCESS = 'GET_HOTEL_SUCCESS';
// Type
export const GET_ALL_TYPE = 'GET_ALL_TYPE';
export const GET_ALL_TYPE_SUCCESS = 'GET_ALL_TYPE_SUCCESS';
// Facility
export const GET_ALL_FACILITY = 'GET_ALL_FACILITY';
export const GET_ALL_FACILITY_SUCCESS = 'GET_ALL_FACILITY_SUCCESS';
export const CREATE_FACILITY = 'CREATE_FACILITY';
export const CREATE_FACILITY_SUCCESS = 'CREATE_FACILITY_SUCCESS';
export const UPDATE_FACILITY = 'UPDATE_FACILITY';
export const UPDATE_FACILITY_SUCCESS = 'UPDATE_FACILITY_SUCCESS';
export const HOTEL_ERROR = 'HOTEL_ERROR';
// Room
export const GET_ALL_ROOM = 'GET_ALL_ROOM';
export const GET_ALL_ROOM_SUCCESS = 'GET_ALL_ROOM_SUCCESS';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
