// Hotel
export const GET_ALL_HOTEL = 'GET_ALL_HOTEL';
export const GET_ALL_HOTEL_SUCCESS = 'GET_ALL_HOTEL_SUCCESS';
// Type
export const GET_ALL_TYPE = 'GET_ALL_TYPE';
export const GET_ALL_TYPE_SUCCESS = 'GET_ALL_TYPE_SUCCESS';
// Facility
export const GET_ALL_FACILITY = 'GET_ALL_FACILITY';
export const GET_ALL_FACILITY_SUCCESS = 'GET_ALL_FACILITY_SUCCESS';
export const CREATE_FACILITY = 'CREATE_FACILITY';
export const CREATE_FACILITY_SUCCESS = 'CREATE_FACILITY_SUCCESS';
export const HOTEL_ERROR = 'HOTEL_ERROR';
