export const GET_ALL_TOUR_CATEGORY = 'GET_ALL_TOUR_CATEGORY';
export const GET_ALL_TOUR_CATEGORY_SUCCESS = 'GET_ALL_TOUR_CATEGORY_SUCCESS';
export const GET_ALL_TOUR_CATEGORY_FAILED = 'GET_ALL_TOUR_CATEGORY_FAILED';
export const CREATE_TOUR_CATEGORY = 'CREATE_TOUR_CATEGORY';
export const CREATE_TOUR_CATEGORY_SUCCESS = 'CREATE_TOUR_CATEGORY_SUCCESS';
export const CREATE_TOUR_CATEGORY_FAILED = 'CREATE_TOUR_CATEGORY_FAILED';
