//Tour
export const GET_ALL_TOUR = 'GET_ALL_TOUR';
export const GET_ALL_TOUR_SUCCESS = 'GET_ALL_TOUR_SUCCESS';
export const GET_ALL_TOUR_FAILED = 'GET_ALL_TOUR_FAILED';
export const GET_TOUR = 'GET_TOUR';
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';
export const GET_TOUR_FAILED = 'GET_TOUR_FAILED';
export const CREATE_TOUR = 'CREATE_TOUR';
export const CREATE_TOUR_SUCCESS = 'CREATE_TOUR_SUCCESS';
export const CREATE_TOUR_FAILED = 'CREATE_TOUR_FAILED';
export const UPDATE_TOUR = 'UPDATE_TOUR';
export const UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS';
// Tour Schedule
export const TOUR_SCHEDULE = 'TOUR_SCHEDULE';
export const TOUR_SCHEDULE_SUCCESS = 'TOUR_SCHEDULE_SUCCESS';
export const ADD_TOUR_SCHEDULE = 'ADD_TOUR_SCHEDULE';
export const ADD_TOUR_SCHEDULE_SUCCESS = 'ADD_TOUR_SCHEDULE_SUCCESS';
//Tour category
export const GET_ALL_TOUR_CATEGORY = 'GET_ALL_TOUR_CATEGORY';
export const GET_ALL_TOUR_CATEGORY_SUCCESS = 'GET_ALL_TOUR_CATEGORY_SUCCESS';
export const CREATE_TOUR_CATEGORY = 'CREATE_TOUR_CATEGORY';
export const CREATE_TOUR_CATEGORY_SUCCESS = 'CREATE_TOUR_CATEGORY_SUCCESS';
export const UPDATE_TOUR_CATEGORY = 'UPDATE_TOUR_CATEGORY';
export const UPDATE_TOUR_CATEGORY_SUCCESS = 'UPDATE_TOUR_CATEGORY_SUCCESS';
//Tour attribute
export const GET_ALL_TOUR_ATTRIBUTE = 'GET_ALL_TOUR_ATTRIBUTE';
export const GET_ALL_TOUR_ATTRIBUTE_SUCCESS = 'GET_ALL_TOUR_ATTRIBUTE_SUCCESS';
export const CREATE_TOUR_ATTRIBUTE = 'CREATE_TOUR_ATTRIBUTE';
export const CREATE_TOUR_ATTRIBUTE_SUCCESS = 'CREATE_TOUR_ATTRIBUTE_SUCCESS';
export const UPDATE_TOUR_ATTRIBUTE = 'UPDATE_TOUR_ATTRIBUTE';
export const UPDATE_TOUR_ATTRIBUTE_SUCCESS = 'UPDATE_TOUR_ATTRIBUTE_SUCCESS';
// Error handler
export const TOUR_HANDLE_FAILED = 'TOUR_HANDLE_FAILED';
