export const GET_LIST_ORDER = 'GET_LIST_ORDER';
export const GET_LIST_ORDER_SUCCESS = 'GET_LIST_ORDER_SUCCESS';
export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';
