export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const UPDATE_ROLE_USER = 'UPDATE_ROLE_USER';
export const UPDATE_ROLE_USER_SUCCESS = 'UPDATE_ROLE_USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';
