export const GET_LIST_REVIEWS = 'GET_LIST_REVIEWS';
export const GET_LIST_REVIEWS_SUCCESS = 'GET_LIST_REVIEWS_SUCCESS';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const REVIEW_FAILED = 'REVIEW_FAILED';
